# Generated by Django 4.2.18 on 2025-02-03 05:46

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion
import master.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_type', models.CharField(choices=[('HomePage', 'HomePage'), ('About', 'About'), ('Testimonials', 'Testimonials'), ('FAQ', 'FAQ'), ('Blogs', 'Blogs'), ('Blog Detail', 'Blog Detail'), ('Our Teams', 'Our Teams'), ('Contact', 'Contact'), ('Country', 'Country'), ('Country Detail', 'Country Detail'), ('Visa Type/Service/Coaching', 'Visa Type/Service/Coaching'), ('Visa Type/Service/Coaching Detail', 'Visa Type/Service/Coaching Detail')], max_length=150)),
                ('title', models.CharField(max_length=150)),
                ('description', ckeditor_uploader.fields.RichTextUploadingField()),
                ('image', models.ImageField(null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('slug', models.SlugField(null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('alternative_phone', models.CharField(max_length=15, null=True)),
                ('google_map_url', models.CharField(blank=True, max_length=1000, null=True)),
                ('favicon_icon', models.ImageField(null=True, upload_to=master.models.rename_file)),
                ('logo_icon', models.ImageField(null=True, upload_to=master.models.rename_file)),
                ('address', models.TextField(blank=True, null=True)),
                ('footer_description', models.TextField(blank=True, null=True)),
                ('footer_image', models.ImageField(null=True, upload_to=master.models.rename_file)),
                ('country_code', models.CharField(max_length=10, null=True)),
                ('gmail_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email (Send Mail)')),
                ('password', models.CharField(blank=True, max_length=350, verbose_name='Password (Send Mail)')),
                ('office_hours', models.CharField(max_length=150, null=True)),
                ('page_type', models.CharField(choices=[('Service', 'Service'), ('Visa', 'Visa'), ('Coaching', 'Coaching')], default='Visa', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ContactForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('subject', models.CharField(max_length=15)),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answer', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Headings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading_type', models.CharField(choices=[('NewsLetter', 'NewsLetter'), ('Contact', 'Contact'), ('Country', 'Country'), ('Teams', 'Teams'), ('Connected Company', 'Connected Company'), ('FAQ', 'FAQ'), ('Testimonials', 'Testimonials'), ('Process', 'Process'), ('Visa Type/Service/Coaching', 'Visa Type/Service/Coaching'), ('Numbers', 'Numbers')], max_length=150)),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('image', models.ImageField(null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='NewsLetter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=150)),
                ('total', models.FloatField(default=0)),
                ('bedroom', models.IntegerField(default=0)),
                ('bathroom', models.IntegerField(default=0)),
                ('short_description', models.TextField(null=True)),
                ('description', ckeditor_uploader.fields.RichTextUploadingField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.category')),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_type', models.CharField(choices=[('FAQ', 'FAQ'), ('Blogs', 'Blogs'), ('Testimonials', 'Testimonials'), ('Our Teams', 'Our Teams'), ('Connected Company', 'Connected Company'), ('VisaType', 'VisaType'), ('Numbers', 'Numbers'), ('Process', 'Process'), ('About', 'About'), ('Country', 'Country'), ('Blogs', 'Blogs')], max_length=150, null=True)),
                ('show', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='SEO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_type', models.CharField(choices=[('Home', 'Home'), ('About', 'About'), ('Blogs', 'Blogs'), ('Contact', 'Contact'), ('Visa Type/Service/Coaching', 'Visa Type/Service/Coaching'), ('Our Teams', 'Our Teams'), ('FAQ', 'FAQ'), ('Testimonials', 'Testimonials'), ('Country', 'Country')], max_length=200, null=True)),
                ('meta_title', models.TextField(blank=True, max_length=500, null=True)),
                ('meta_description', models.TextField(blank=True, max_length=500, null=True)),
                ('meta_keywords', models.TextField(blank=True, max_length=500, null=True)),
                ('canonical_tag', models.TextField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('social_media', models.CharField(choices=[('Facebook', 'Facebook'), ('Instagram', 'Instagram'), ('Linkedin', 'Linkedin'), ('Twitter', 'Twitter'), ('Youtube', 'Youtube'), ('Telegram', 'Telegram'), ('Whatsapp', 'Whatsapp'), ('Threads', 'Threads')], max_length=100, null=True)),
                ('url', models.URLField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Testimonials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('designation', models.CharField(max_length=50)),
                ('review', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to=master.models.rename_file)),
            ],
        ),
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=master.models.rename_file)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.property')),
            ],
        ),
    ]
