# Generated by Django 4.2.18 on 2025-02-03 06:22

from django.db import migrations, models
import master.models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='thumbnail_image',
            field=models.ImageField(null=True, upload_to=master.models.rename_file),
        ),
    ]
