# Generated by Django 4.2.18 on 2025-02-03 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0002_property_thumbnail_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='section_type',
            field=models.CharField(choices=[('Property', 'Property'), ('FAQ', 'FAQ'), ('Blogs', 'Blogs'), ('Testimonials', 'Testimonials'), ('Our Teams', 'Our Teams'), ('Connected Company', 'Connected Company'), ('VisaType', 'VisaType'), ('Numbers', 'Numbers'), ('Process', 'Process'), ('About', 'About'), ('Country', 'Country'), ('Blogs', 'Blogs')], max_length=150, null=True),
        ),
    ]
