# Generated by Django 4.2.18 on 2025-02-03 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0004_property_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
