# Generated by Django 4.2.18 on 2025-02-04 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0005_alter_property_created_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='page_type',
        ),
    ]
