# Generated by Django 4.2.18 on 2025-02-04 07:10

from django.db import migrations, models
import master.models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0006_remove_company_page_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=master.models.rename_file)),
                ('favourite', models.BooleanField(default=False)),
            ],
        ),
    ]
