# Generated by Django 4.2.18 on 2025-02-05 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0007_gallery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='section_type',
            field=models.CharField(choices=[('Property', 'Property'), ('Gallery', 'Gallery'), ('About', 'About'), ('FAQ', 'FAQ'), ('Blogs', 'Blogs'), ('Testimonials', 'Testimonials'), ('Our Teams', 'Our Teams'), ('Connected Company', 'Connected Company'), ('VisaType', 'VisaType'), ('Numbers', 'Numbers'), ('Process', 'Process'), ('Country', 'Country')], max_length=150, null=True),
        ),
    ]
