# Generated by Django 4.2.18 on 2025-02-05 06:51

from django.db import migrations, models
import master.models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0008_alter_section_section_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeProvide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to=master.models.rename_file)),
            ],
        ),
    ]
