# Generated by Django 4.2.18 on 2025-02-05 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0010_alter_section_section_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='headings',
            name='heading_type',
            field=models.CharField(choices=[('For rates & Availability', 'For rates & Availability'), ('About', 'About'), ('NewsLetter', 'NewsLetter'), ('Contact', 'Contact'), ('Country', 'Country'), ('Teams', 'Teams'), ('Connected Company', 'Connected Company'), ('FAQ', 'FAQ'), ('Testimonials', 'Testimonials'), ('Process', 'Process'), ('Visa Type/Service/Coaching', 'Visa Type/Service/Coaching'), ('Numbers', 'Numbers')], max_length=150),
        ),
    ]
