# Generated by Django 4.2.18 on 2025-02-05 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0011_alter_headings_heading_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Numbers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('number', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='headings',
            name='heading_type',
            field=models.CharField(choices=[('For rates & Availability', 'For rates & Availability'), ('About', 'About'), ('Apartment', 'Apartment'), ('Contact', 'Contact'), ('Testimonials', 'Testimonials'), ('Numbers', 'Numbers')], max_length=150),
        ),
        migrations.AlterField(
            model_name='section',
            name='section_type',
            field=models.CharField(choices=[('Property', 'Property'), ('Gallery', 'Gallery'), ('About', 'About'), ('WeProvide', 'WeProvide'), ('AboutHome', 'AboutHome'), ('FAQ', 'FAQ'), ('Blogs', 'Blogs'), ('Testimonials', 'Testimonials'), ('Our Teams', 'Our Teams'), ('Connected Company', 'Connected Company'), ('VisaType', 'VisaType'), ('Numbers', 'Numbers'), ('Process', 'Process'), ('Country', 'Country')], max_length=150, null=True),
        ),
    ]
