# Generated by Django 4.2.18 on 2025-02-07 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0013_alter_headings_heading_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApartmentBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('family_member', models.PositiveIntegerField()),
                ('children', models.PositiveIntegerField()),
                ('message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='headings',
            name='heading_type',
            field=models.CharField(choices=[('For rates & Availability', 'For rates & Availability'), ('About', 'About'), ('Apartment', 'Apartment'), ('Numbers', 'Numbers'), ('Gallery', 'Gallery'), ('Contact', 'Contact'), ('Testimonials', 'Testimonials'), ('Numbers', 'Numbers'), ('Blogs', 'Blogs')], max_length=150),
        ),
    ]
