# Generated by Django 4.2.18 on 2025-02-07 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0014_apartmentbooking_alter_headings_heading_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
