# Generated by Django 4.2.18 on 2025-02-07 07:01

from django.db import migrations, models
import master.models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0015_property_slug'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ApartmentBooking',
        ),
        migrations.AlterField(
            model_name='banners',
            name='image',
            field=models.ImageField(null=True, upload_to=master.models.rename_file),
        ),
    ]
