# Generated by Django 4.2.18 on 2025-02-07 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0016_delete_apartmentbooking_alter_banners_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='canonical_tag',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='meta_description',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='meta_keywords',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='meta_title',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='banners',
            name='banner_type',
            field=models.CharField(choices=[('HomePage', 'HomePage'), ('About', 'About'), ('Apartments', 'Apartments'), ('Apartment Detail', 'Apartment Detail'), ('Gallery', 'Gallery'), ('Blogs', 'Blogs'), ('Blog Detail', 'Blog Detail'), ('Contact', 'Contact')], max_length=150),
        ),
        migrations.AlterField(
            model_name='seo',
            name='page_type',
            field=models.CharField(choices=[('HomePage', 'HomePage'), ('About', 'About'), ('Apartments', 'Apartments'), ('Gallery', 'Gallery'), ('Blogs', 'Blogs'), ('Blog Detail', 'Blog Detail'), ('Contact', 'Contact')], max_length=200, null=True),
        ),
    ]
