# Generated by Django 4.2.18 on 2025-02-05 04:52

import about.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField(null=True)),
                ('house_admin', models.ImageField(upload_to=about.models.rename_file)),
                ('admin_name', models.CharField(max_length=150)),
                ('admin_designation', models.CharField(max_length=150)),
                ('admin_description', models.TextField(null=True)),
                ('admin_signature', models.ImageField(upload_to=about.models.rename_file)),
            ],
        ),
    ]
