# Generated by Django 4.2.18 on 2025-02-05 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_abouthome'),
    ]

    operations = [
        migrations.AddField(
            model_name='abouthome',
            name='sequence',
            field=models.IntegerField(default=0),
        ),
    ]
