# Generated by Django 4.2.18 on 2025-02-05 10:06

import about.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_abouthome_sequence'),
    ]

    operations = [
        migrations.AddField(
            model_name='abouthome',
            name='image',
            field=models.ImageField(null=True, upload_to=about.models.rename_file),
        ),
    ]
